default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['DB_POOL'] || ENV['MAX_THREADS'] || 5 %>
  timeout: 5000
  port: 5432

development:
  <<: *default
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  database: funny_videos_development

test:
  <<: *default
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  database: funny_videos_test

production:
  <<: *default
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  database: funny_videos
